const en={
  connecting:'Connecting',timeout:'The request timed out. Your input and drafts were kept; try again.',rateLimited:'The service is busy. Wait a moment and try again; your input was kept.',invalidKey:'DeepSeek rejected the key. Check DEEPSEEK_API_KEY and restart the planner.',providerUnavailable:'DeepSeek is temporarily unavailable. Your input and drafts were kept.',
  pendingSchedule:'Schedule pending',
  sessionWeeks:'Weeks vary by session',undoStale:'This item has changed since saving. Undo was stopped to preserve your latest edits.',
  repeatLabel:'Repeat',repeatDaily:'Daily',repeatWeekdays:'Weekdays',repeatWeekly:'Weekly',repeatNone:'Does not repeat',titleLabel:'Title',courseLabel:'Linked course',dateLabel:'Date',timeLabel:'Time',priorityLabel:'Priority',leadLabel:'Lead time (minutes)',notesLabel:'Notes',storageFailed:'The browser could not save the changes. Free some storage and try again.',before:'Before',after:'After',unknown:'Not specified',
  title:'AI assistant',subtitle:'Your classes, tasks and next steps',newChat:'New conversation',welcome:'What would you like to arrange?',intro:'Check your schedule, turn a thought into a reminder, or make room for studying.',query:'Check my schedule',create:'Create a reminder',extract:'Read a timetable',study:'Plan my study',queryPrompt:'What classes and reminders do I have today?',createPrompt:'Help me create a reminder. Ask me for the title, date and time.',extractPrompt:'Help me import a timetable. I will paste text or attach screenshots.',studyPrompt:'Plan seven 45-minute study sessions over the next seven days, avoiding my classes.',placeholder:'Ask about your schedule, or paste timetable text…',send:'Send',stop:'Stop',attach:'Attach screenshots',remove:'Remove',privacy:'Your request, relevant course and reminder data, and attached screenshots will be sent to DeepSeek. Screenshots and conversations are not stored on the server.',consent:'Allow sending to DeepSeek',limits:'PNG, JPEG, WebP · up to 4 images · 6 MB total',thinking:'Working on your request…',pending:'Review before saving',saved:'Saved',cancelled:'Cancelled',undone:'Undone',confirm:'Confirm changes',cancel:'Cancel',undo:'Undo',edit:'Edit',import:'Import courses',plan:'Study plan',addPlan:'Add reminders',courses:'Courses',reminders:'Reminders',empty:'No changes have been saved.',duplicate:'Duplicate course',conflict:'Time conflict',incomplete:'Complete the missing fields',warnings:'Please check',linkedDelete:'These linked reminders will also be deleted',ready:'Ready',offline:'Not configured',missingKey:'Set DEEPSEEK_API_KEY in Windows environment variables, then restart the course planner.',error:'Request failed. Your input and drafts have been kept.',stopped:'Stopped. Your input and drafts have been kept.',stale:'Data changed. The preview has been refreshed; review and confirm again.',noSlots:'No available study slots. Try fewer sessions or a wider time range.',partial:'Only part of the requested plan fits the available time.',imageLimit:'Use up to 4 screenshots, with a combined size of 6 MB or less.',imageType:'Only PNG, JPEG and WebP screenshots are supported.',needConsent:'Allow sending to DeepSeek before your first request.',invalid:'The response was incomplete or invalid. No unvalidated changes were saved.',duplicateCourse:'Remove or edit duplicate courses before importing.',stalePlan:'The schedule has changed. Generate a fresh study plan before saving.',termChanged:'The active term changed. Send your request again for the new term.',roundLimit:'The assistant reached its tool limit. Saved results are shown below; continue with a more specific request.',retry:'Retry',you:'You',assistant:'Assistant',delete:'Delete',complete:'Complete',update:'Update',add:'Add',noTime:'Time unreadable',unknownWeeks:'Weeks unreadable',busyHint:'You can stop at any time.',planSaved:'Reminders added',dataUnavailable:'Could not reach the AI service. Restart the planner and try again.'
};
type Labels=typeof en;
const zhCN:Labels={
  connecting:'连接中',timeout:'请求超时，输入和草稿已保留，可以重试。',rateLimited:'服务暂时限流，请稍后重试，输入已保留。',invalidKey:'DeepSeek 未接受当前密钥，请检查 DEEPSEEK_API_KEY 并重新启动课程表。',providerUnavailable:'DeepSeek 暂时无法处理请求，输入和草稿已保留。',
  pendingSchedule:'时间待定',
  sessionWeeks:'按各时段周次上课',undoStale:'这项数据在保存后已被修改，无法直接撤销。你的最新改动已保留。',
  repeatLabel:'重复',repeatDaily:'每天',repeatWeekdays:'工作日',repeatWeekly:'每周',repeatNone:'不重复',titleLabel:'标题',courseLabel:'关联课程',dateLabel:'日期',timeLabel:'时间',priorityLabel:'优先级',leadLabel:'提前提醒（分钟）',notesLabel:'备注',storageFailed:'浏览器未能保存改动，请释放存储空间后重试。',before:'原安排',after:'新安排',unknown:'未填写',
  title:'AI 助手',subtitle:'把课程、待办和学习安排连起来',newChat:'新对话',welcome:'接下来，想安排什么？',intro:'查一查课程，把想法记成提醒，或为复习留出时间。',query:'查询安排',create:'创建提醒',extract:'识别课表',study:'安排复习',queryPrompt:'我今天有哪些课程和提醒事项？',createPrompt:'帮我创建一个提醒，请先问我标题、日期和时间。',extractPrompt:'帮我导入课表，我会粘贴文字或上传截图。',studyPrompt:'为我安排未来七天的七次复习，每次45分钟，避开课程。',placeholder:'询问课程和待办，或粘贴课表文字…',send:'发送',stop:'停止',attach:'上传截图',remove:'移除',privacy:'请求内容、相关课程和提醒数据，以及上传的截图将发送给 DeepSeek。服务器不保存截图和对话。',consent:'允许发送给 DeepSeek',limits:'PNG、JPEG、WebP · 最多 4 张 · 合计 6 MB',thinking:'正在处理你的请求…',pending:'保存前请确认',saved:'已保存',cancelled:'已取消',undone:'已撤销',confirm:'确认改动',cancel:'取消',undo:'撤销',edit:'编辑',import:'导入课程',plan:'学习计划',addPlan:'加入提醒',courses:'课程',reminders:'提醒事项',empty:'尚未保存改动。',duplicate:'重复课程',conflict:'时间冲突',incomplete:'请补全缺失信息',warnings:'请检查',linkedDelete:'以下关联提醒也将删除',ready:'可用',offline:'未配置',missingKey:'请在 Windows 环境变量中设置 DEEPSEEK_API_KEY，然后重新启动课程表。',error:'请求失败，输入与草稿已保留。',stopped:'已停止，输入与草稿已保留。',stale:'数据已经变化，预览已更新。请重新检查并确认。',noSlots:'没有足够的空闲时间，请减少次数或扩大时间范围。',partial:'空闲时间仅能安排部分学习次数。',imageLimit:'最多上传 4 张截图，总大小不超过 6 MB。',imageType:'仅支持 PNG、JPEG 和 WebP 截图。',needConsent:'首次请求前，请允许发送给 DeepSeek。',invalid:'回答不完整或格式无效，未经校验的改动没有保存。',duplicateCourse:'请移除或编辑重复课程后再导入。',stalePlan:'课程或待办已经变化，请重新生成学习计划后保存。',termChanged:'当前学期已经切换，请在新学期重新发送请求。',roundLimit:'已达到本次工具调用上限，已保存的结果显示在下方。请继续提出更具体的请求。',retry:'重试',you:'我',assistant:'助手',delete:'删除',complete:'完成',update:'修改',add:'新增',noTime:'时间未识别',unknownWeeks:'周次未识别',busyHint:'可以随时停止。',planSaved:'已加入提醒',dataUnavailable:'无法连接 AI 服务，请重新启动课程表后再试。'
};
const zhTW:Labels={...zhCN,title:'AI 助手',subtitle:'把課程、待辦和學習安排連起來',newChat:'新對話',welcome:'接下來，想安排什麼？',intro:'查一查課程，把想法記成提醒，或為複習留出時間。',query:'查詢安排',create:'建立提醒',extract:'辨識課表',study:'安排複習',queryPrompt:'我今天有哪些課程和提醒事項？',createPrompt:'幫我建立一個提醒，請先問我標題、日期和時間。',extractPrompt:'幫我匯入課表，我會貼上文字或上傳截圖。',studyPrompt:'為我安排未來七天的七次複習，每次45分鐘，避開課程。',placeholder:'詢問課程和待辦，或貼上課表文字…',send:'傳送',stop:'停止',attach:'上傳截圖',remove:'移除',consent:'允許傳送給 DeepSeek',pending:'儲存前請確認',saved:'已儲存',cancelled:'已取消',undone:'已復原',confirm:'確認變更',undo:'復原',edit:'編輯',import:'匯入課程',plan:'學習計畫',addPlan:'加入提醒',courses:'課程',reminders:'提醒事項',ready:'可用',offline:'未設定'};
export const AI_TRANSLATIONS:Partial<Record<string,Labels>>={en,'zh-CN':zhCN,'zh-TW':zhTW};
export function aiLabel(language:string,key:string):string {return (AI_TRANSLATIONS[language]||en)[key as keyof Labels]||en[key as keyof Labels]||key;}
