const en = {
  checked: 'Last attempt',
  expand: 'Show more', collapse: 'Show less',
  partialDetails: 'Some historical records contain only a total. Missing input/output details are not estimated.',
  title: 'Usage & balances', subtitle: 'Account balances and Codex activity', refresh: 'Refresh', refreshing: 'Refreshing', balances: 'Provider balances', quota: 'Codex allowance', tokens: 'Token activity', connect: 'Connect', reconnect: 'Reconnect', loginHint: 'Finish signing in in the Edge window and open the balance page. The window closes after reading the balance.', account: 'Account summary', local: 'This computer', today: 'Today', seven: '7 days', thirty: '30 days', all: 'All records', total: 'Total tokens', input: 'Input', cached: 'Cached input', output: 'Output', reasoning: 'Reasoning output', trend: 'Daily activity', models: 'By model', projects: 'By project', unavailable: 'Unavailable', remaining: 'remaining', resets: 'Resets', updated: 'Updated', never: 'Not read yet', ready: 'Connected', stale: 'Last known value', missing_key: 'API key missing or rejected', needs_login: 'Sign in required', login_open: 'Waiting for sign-in', timeout: 'Request timed out', invalid_data: 'Balance or usage could not be identified', no_cli: 'Codex CLI not found', sourceAccount: 'Official Codex account activity. Daily dates follow the official reporting calendar.', sourceLocal: 'Current and archived Codex logs on this computer. This is not your full account usage.', subset: 'Cached input is included in input; reasoning is included in output.', coverage: 'Available daily records', periodMissing: 'The official daily records do not cover this entire period.', empty: 'No token records in this period', noQuota: 'Sign in to Codex on this computer, then refresh. If the account does not provide quota data, its allowance cannot be shown.', apiHint: 'Set DEEPSEEK_API_KEY and restart the planner.', consoleHint: 'Refreshes every minute while this page is visible. Official billing may be delayed.', qwenAccount: 'Alibaba Cloud account', qwenCredit: 'Available account funds', funds: 'Balance', granted: 'Granted', toppedUp: 'Topped up', failed: 'Could not refresh. The last result has been kept.', browserFailed: 'Could not open Edge. Check that Edge is installed and its connection window is closed, then retry.', peak: 'Peak daily tokens', sessions: 'Sessions', recordsNote: 'Showing the latest 30 days with records', lifetime: 'Lifetime tokens', pending: 'Reading account data…', unknownModel: 'Unknown model', unknownProject: 'Unknown project', minutes: 'min window', hours: 'h window', days: 'day window', scopeHint: 'Account and local data overlap and are never added together.', openConsole: 'Official console', fallback: 'View local details', readIssue: 'Refresh issue', creditsNote: 'Allowance percentages are not token counts.'
};
type Labels = typeof en;
const zhCN: Labels = {
  checked: '最近尝试',
  expand: '展开更多', collapse: '收起',
  partialDetails: '部分历史记录仅含总量，缺失的输入、输出明细不做估算。',
  title: '用量与余额', subtitle: '账户余额与 Codex 使用情况', refresh: '刷新', refreshing: '正在刷新', balances: '厂商余额', quota: 'Codex 剩余额度', tokens: 'Token 统计', connect: '连接', reconnect: '重新连接', loginHint: '请在 Edge 窗口完成登录并打开余额页，读取成功后窗口会自动关闭。', account: '账户汇总', local: '本机明细', today: '今日', seven: '近七天', thirty: '近三十天', all: '全部记录', total: '总 Token', input: '输入', cached: '缓存输入', output: '输出', reasoning: '推理输出', trend: '每日趋势', models: '模型排行', projects: '项目排行', unavailable: '暂不可用', remaining: '剩余', resets: '重置时间', updated: '更新于', never: '尚未读取', ready: '已连接', stale: '上次读取结果', missing_key: '密钥缺失或未被接受', needs_login: '需要登录', login_open: '等待登录', timeout: '请求超时', invalid_data: '未能识别余额或用量', no_cli: '未找到 Codex CLI', sourceAccount: '来自 Codex 官方账户统计，每日日期沿用官方口径。', sourceLocal: '来自本机 Codex 当前及归档会话，不代表完整账户用量。', subset: '缓存已包含在输入中，推理已包含在输出中，不重复计入总量。', coverage: '可用每日记录', periodMissing: '官方每日记录未覆盖整个所选时间段。', empty: '这个时间段暂无 Token 记录', noQuota: '请先在本机登录 Codex，再刷新。账户未提供额度数据时，无法显示剩余额度。', apiHint: '设置 DEEPSEEK_API_KEY 后重新启动课程表。', consoleHint: '页面可见时每分钟自动刷新；官方账单结算可能存在延迟。', qwenAccount: '阿里云账户', qwenCredit: '账户可用额度', funds: '余额', granted: '赠送余额', toppedUp: '充值余额', failed: '刷新失败，上次结果已保留。', browserFailed: '无法打开 Edge，请检查是否已安装 Edge、连接窗口是否已关闭，然后重试。', peak: '单日最高 Token', sessions: '会话数', recordsNote: '显示最近 30 个有记录的日期', lifetime: '账户累计 Token', pending: '正在读取账户数据…', unknownModel: '未知模型', unknownProject: '未知项目', minutes: '分钟窗口', hours: '小时窗口', days: '天窗口', scopeHint: '账户与本机统计存在重叠，分别展示，不相加。', openConsole: '官方控制台', fallback: '查看本机明细', readIssue: '本次读取', creditsNote: '剩余百分比不等于可用 Token 数。'
};
const zhTW: Labels = { ...zhCN, title: '用量與餘額', balances: '廠商餘額', quota: 'Codex 剩餘額度', tokens: 'Token 統計', refresh: '重新整理', refreshing: '正在重新整理', connect: '連線', reconnect: '重新連線', account: '帳戶彙總', local: '本機明細', today: '今日', seven: '近七天', thirty: '近三十天', all: '全部記錄', input: '輸入', output: '輸出', cached: '快取輸入', reasoning: '推理輸出', total: '總 Token', unavailable: '暫不可用', trend: '每日趨勢', models: '模型排行', projects: '專案排行', updated: '更新於', remaining: '剩餘', resets: '重設時間', ready: '已連線', stale: '上次讀取結果', needs_login: '需要登入', login_open: '等待登入' };
export const usageLabel = (language: string, key: string): string => (language === 'zh-CN' ? zhCN : language === 'zh-TW' ? zhTW : en)[key as keyof Labels] || key;
