import assert from 'node:assert/strict';
import { OperationLedger, prepareProposal, querySchedule, courseIssues, buildStudyPlan, reminderOccurrences, validWeeks, fingerprint, explicitReminderIntent } from '../src/ai/operations';
import { validateTool, validDate, validateImages, readSSE, MAX_IMAGE_BYTES, type BrowserContext, type Snapshot } from '../src/ai/protocol';
import { DEFAULT_ACADEMIC_CALENDAR } from '../src/data/academicCalendar';

let passed=0;
function test(name:string,fn:()=>void){fn();passed++;console.log(`PASS ${name}`);}
const term='fictional-term';
const env:BrowserContext={term,today:DEFAULT_ACADEMIC_CALENDAR[5].startDate,time:'08:00',timezone:'Asia/Shanghai',language:'zh-CN',adjust:true};
const state:Snapshot={courses:[{id:'c1',name:'测试课程',code:'TEST',term,weeks:'1-16周',credits:0,color:'#527e45',reminderEnabled:true,reminderLeadTimeMinutes:15,meetings:[{id:'m1',day:'M',startTime:'09:00',endTime:'10:00',location:'测试教室',type:'lecture',weeks:'1-8周'}]}],assignments:[]};
const base={title:'测试提醒',courseId:'',dueDate:env.today,dueTime:'18:00',repeat:'none',priority:'medium',reminderMinutesBefore:10,notes:''};
const tool=validateTool('create_reminder',base),plans=new Map();
test('Reject incomplete/unknown tool parameters',()=>{assert.throws(()=>validateTool('create_reminder',{title:'x'}));assert.throws(()=>validateTool('create_reminder',{...base,other:'x'}));assert.throws(()=>validateTool('nonexistent',{}));});
test('Auto-save requires explicit reminder intent, not a planning question',()=>{assert.ok(explicitReminderIntent('提醒我明天18点读书'));assert.ok(explicitReminderIntent('Set a reminder tomorrow at 18:00'));assert.ok(!explicitReminderIntent('我应该添加提醒吗？'));assert.ok(!explicitReminderIntent('安排未来七天学习计划'));});
test('Reject invalid real calendar dates and time',()=>{assert.equal(validDate('2026-02-30'),false);assert.throws(()=>validateTool('create_reminder',{...base,dueTime:'25:00'}));});
test('Reject unsupported screenshots/count/total size',()=>{assert.throws(()=>validateImages([{name:'x',url:'data:image/svg+xml;base64,AAAA'}]));assert.throws(()=>validateImages(Array(5).fill({name:'x',url:'data:image/png;base64,AAAA'})));assert.throws(()=>validateImages([{name:'x',url:'data:image/png;base64,'+'A'.repeat(Math.ceil((MAX_IMAGE_BYTES+3)*4/3))}]));});
test('New reminder is a real transaction, replay is rejected, undo preserves unrelated tasks',()=>{
  const p=prepareProposal(tool,'op1',state,env,plans),ledger=new OperationLedger();assert.equal(state.assignments.length,0);
  const saved=ledger.apply(p,state);assert.equal(saved.assignments.length,1);assert.equal(saved.assignments[0].title,base.title);
  assert.throws(()=>ledger.apply(p,state),/duplicate_operation/);
  const unrelated={...saved.assignments[0],id:'manual'};
  const undone=ledger.undo(p,{...saved,assignments:[...saved.assignments,unrelated]});assert.deepEqual(undone.assignments,[unrelated]);assert.throws(()=>ledger.apply(p,undone),/duplicate_operation/);
});
test('Stale confirmation cannot overwrite manual changes',()=>{const p=prepareProposal(tool,'stale',state,env,plans);assert.throws(()=>new OperationLedger().apply(p,{...state,courses:[]} ),/stale_data/);});
test('Undo refuses changed targets',()=>{const p=prepareProposal(tool,'undo',state,env,plans),l=new OperationLedger(),saved=l.apply(p,state);assert.throws(()=>l.undo(p,{...saved,assignments:saved.assignments.map(x=>({...x,title:'手动修改'}))}),/stale_data/);});
test('Missing and other-term targets cannot be written',()=>{assert.throws(()=>prepareProposal(validateTool('create_reminder',{...base,courseId:'missing'}),'missing',state,env,plans));assert.throws(()=>prepareProposal(validateTool('delete_course',{id:'c1'}),'other',state,{...env,term:'other'},plans));});
const withReminder={...state,assignments:[{...base,courseId:'c1',id:'r1',type:'other' as const,priority:'medium' as const,repeat:'daily' as const,completed:false}]};
test('Delete course previews linked reminder cascade, no write until apply',()=>{const p=prepareProposal(validateTool('delete_course',{id:'c1'}),'delete',withReminder,env,plans);assert.deepEqual(p.warnings,['测试提醒']);assert.equal(p.after.assignments.length,0);assert.equal(withReminder.assignments.length,1);});
test('Recurring completion uses existing next-occurrence rules',()=>{const p=prepareProposal(validateTool('complete_reminder',{id:'r1'}),'complete',withReminder,env,plans);assert.equal(p.after.assignments[0].dueDate,new Date(new Date(env.today+'T12:00:00Z').getTime()+86400000).toISOString().slice(0,10));assert.equal(p.after.assignments[0].completed,false);assert.deepEqual(p.after.assignments[0].completedDates,[env.today]);});
test('Query applies actual meeting week and recurrence',()=>{assert.equal(querySchedule(withReminder,env,env.today,env.today)[0].classes.length,1);const late=DEFAULT_ACADEMIC_CALENDAR[10].startDate;assert.equal(querySchedule(state,env,late,late)[0].classes.length,0);assert.throws(()=>querySchedule(state,env,'2026-01-01','2026-03-01'));});
test('Weekdays and weekly occurrences retain their anchor and completed dates',()=>{const r=withReminder.assignments[0];const friday='2026-10-09';assert.deepEqual(reminderOccurrences({...r,dueDate:friday,repeat:'weekdays'},friday,'2026-10-12').map(x=>x.dueDate),[friday,'2026-10-12']);assert.deepEqual(reminderOccurrences({...r,dueDate:friday,repeat:'weekly',completedDates:[friday]},friday,'2026-10-16').map(x=>x.dueDate),['2026-10-16']);});
const study={title:'复习测试',courseId:'c1',startDate:env.today,days:7,sessions:7,durationMinutes:45,gapMinutes:10,dayStart:'09:00',dayEnd:'21:00'};
test('Study slots avoid classes plus padding and each other',()=>{const slots=buildStudyPlan(study,state,env);assert.equal(slots.length,7);assert.equal(slots[0].startTime,'10:10');for(let i=1;i<slots.length;i++)if(slots[i].date===slots[i-1].date)assert.ok(slots[i].startTime>slots[i-1].endTime);assert.equal(state.assignments.length,0);});
test('Plan is read-only, explicit save works, stale plan refuses save',()=>{const p=prepareProposal(validateTool('plan_study',study),'plan',state,env,plans);plans.set(p.id,p);assert.equal(p.after.assignments.length,0);const saved=prepareProposal(validateTool('save_study_plan',{planId:p.id}),'save-plan',state,env,plans);assert.equal(saved.after.assignments.length,7);const changed={...state,courses:state.courses.map(c=>({...c,meetings:c.meetings.map(m=>({...m,endTime:'12:00'}))}))};assert.throws(()=>prepareProposal(validateTool('save_study_plan',{planId:p.id}),'stale-plan',changed,env,plans),/stale_plan/);});
test('Import incomplete fields never guess times, editable draft validates',()=>{const p=prepareProposal(validateTool('extract_courses',{courses:[{name:'待补全',code:'',weeks:'',meetings:[{day:'M',startTime:'',endTime:'',weeks:'',location:''}]}],uncertainties:['时间看不清']}),'draft',state,env,plans);assert.equal(p.courses![0].meetings[0].startTime,'');assert.equal(courseIssues(p.courses!,state.courses).invalidIds.length,1);const c={...p.courses![0],weeks:'1-16周',meetings:p.courses![0].meetings.map(m=>({...m,startTime:'14:00',endTime:'15:00'}))};assert.equal(courseIssues([c],state.courses).invalidIds.length,0);assert.equal(courseIssues([c],[c]).duplicateIds.length,1);});
test('Conflict checks use session weeks, not just weekday',()=>{const c=state.courses[0],draft={...c,id:'new'};assert.equal(courseIssues([draft],[c]).conflicts.length,1);assert.equal(courseIssues([{...draft,meetings:draft.meetings.map(m=>({...m,weeks:'9-16周'}))}],[c]).conflicts.length,0);assert.equal(validWeeks('未知'),false);assert.equal(validWeeks('1-4,6,7-17周'),true);});
test('Reject reversed meeting times and empty patches',()=>{assert.throws(()=>prepareProposal(validateTool('update_course',{id:'c1',changes:{meetings:[{day:'M',startTime:'11:00',endTime:'09:00',location:'',weeks:'1-8周'}]}}),'reversed',state,env,plans));assert.throws(()=>prepareProposal(validateTool('update_reminder',{id:'r1',changes:{}}),'empty',withReminder,env,plans));});
test('Explicit pending course is importable; unreadable times are not treated as pending',()=>{const p=prepareProposal(validateTool('extract_courses',{courses:[{name:'测试实训',code:'',weeks:'',meetings:[],schedulePending:true}],uncertainties:[]}),'pending',state,env,plans);assert.equal(courseIssues(p.courses!,state.courses).invalidIds.length,0);assert.equal(courseIssues([{...p.courses![0],schedulePending:false}],state.courses).invalidIds.length,1);});
test('Reading a plan for a minute does not invalidate still-future slots',()=>{const p=prepareProposal(validateTool('plan_study',study),'read-plan',state,env,plans);plans.set(p.id,p);assert.equal(prepareProposal(validateTool('save_study_plan',{planId:p.id}),'save-read-plan',state,{...env,time:'08:01'},plans).after.assignments.length,7);assert.throws(()=>prepareProposal(validateTool('save_study_plan',{planId:p.id}),'past-plan',state,{...env,time:'12:00'},plans),/stale_plan/);});
test('New study plans avoid the full duration of already-saved study blocks',()=>{const p=prepareProposal(validateTool('plan_study',study),'duration-plan',state,env,plans);plans.set(p.id,p);const saved=prepareProposal(validateTool('save_study_plan',{planId:p.id}),'duration-save',state,env,plans).after;assert.equal(saved.assignments[0].durationMinutes,45);const next=buildStudyPlan(study,saved,env);assert.equal(next[0].startTime,'11:05');});
test('AI exam reminders retain their type for existing exam filters',()=>{const p=prepareProposal(validateTool('create_reminder',{...base,type:'final'}),'exam',state,env,plans);assert.equal(p.after.assignments[0].type,'final');});
async function streaming(){const bytes=new TextEncoder().encode('data: {"text":"中文"}\n\ndata: [DONE]\n\n'),chunks=Array.from(bytes,b=>new Uint8Array([b]));const stream=new ReadableStream<Uint8Array>({start(c){chunks.forEach(b=>c.enqueue(b));c.close();}});const values:string[]=[];await readSSE(stream,x=>values.push(x));assert.deepEqual(values,['{"text":"中文"}','[DONE]']);console.log('PASS SSE split UTF-8 and packet boundaries');console.log(`${++passed} AI checks passed`);}
streaming().catch(e=>{console.error(e);process.exitCode=1;});
