import assert from 'node:assert/strict';
import { mkdir, rm, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { parseSessionText, aggregateSessions, CodexScanner } from '../src/usage/scanner';
import { accountStats, normalizeAccount, normalizeQuota } from '../src/usage/codex';
import { BalanceService, deepseekBalance, glmConsoleBalance, parseConsoleBalance, waitForBalance, allowedConsoleUrl, emptyBalance } from '../src/usage/balances';
import { loadPrivateState, savePrivateState } from '../src/usage/privateState';
import { UsageService, createUsageRouter } from '../src/usage/server';
import express from 'express';

let checks = 0;
const check = (name: string, fn: () => void) => { fn(); checks++; console.log(`PASS ${name}`); };
const usage = (input: number, output = 10) => ({ input_tokens: input, cached_input_tokens: input / 2, output_tokens: output, reasoning_output_tokens: output / 2, total_tokens: input + output });
const meta = (id: string, parent?: string) => JSON.stringify({ type: 'session_meta', payload: { id, cwd: 'C:\\work\\Project', forked_from_id: parent } });
const ctx = (model: string) => JSON.stringify({ type: 'turn_context', payload: { model } });
const event = (time: string, current: any, last = current) => JSON.stringify({ type: 'event_msg', timestamp: time, payload: { type: 'token_count', info: { total_token_usage: current, last_token_usage: last } } });
const t1 = '2026-10-06T16:01:00Z', t2 = '2026-10-07T03:00:00Z', t3 = '2026-10-07T04:00:00Z', now = Date.parse('2026-10-07T05:00:00Z');
const text = [meta('parent'), ctx('qwen-custom'), event(t1, usage(100)), event(t1, usage(100)), event(t2, usage(200, 20), usage(100)), event(t3, usage(20), usage(20)), '{"type":"event_msg"'].join('\n');
const parent = parseSessionText(text);
const all = () => aggregateSessions([parent], 'all', 'Asia/Shanghai', now);
check('cumulative snapshots and counter resets', () => assert.equal(all().total, 250));
check('cache and reasoning are subsets', () => assert.equal(all().total, all().details!.input + all().details!.output));
check('retain custom provider models used in Codex', () => assert.equal(all().models[0].name, 'qwen-custom'));
check('malformed trailing record does not erase usage', () => assert.equal(parent.malformed, 1));
check('local timezone groups UTC evening into following day', () => assert.deepEqual(all().daily, [{ date: '2026-10-07', tokens: 250 }]));
check('timezone change preserves total and changes dates', () => assert.deepEqual(aggregateSessions([parent], 'all', 'UTC', now).daily, [{ date: '2026-10-06', tokens: 110 }, { date: '2026-10-07', tokens: 140 }]));
check('today range follows browser timezone', () => assert.equal(aggregateSessions([parent], 'today', 'UTC', now).total, 140));
check('duplicate archived/current files counted once', () => assert.equal(aggregateSessions([parent, parent], 'all', 'UTC', now).total, 250));
check('fork inherited history excluded, new turn counted', () => {
  const child = parseSessionText([meta('child', 'parent'), ...text.split('\n').slice(1, -1), event('2026-10-07T04:30:00Z', usage(70, 20), usage(50))].join('\n'));
  assert.equal(aggregateSessions([parent, child], 'all', 'UTC', now).total, 310);
});
check('unknown models and projects stay visible', () => assert.equal(aggregateSessions([parseSessionText(event(t1, usage(10)))], 'all', 'UTC', now).models[0].name, 'Unknown model'));
check('same token numbers at different times are not duplicates', () => assert.equal(parseSessionText([event(t1, usage(10)), event(t2, usage(20, 20), usage(10))].join('\n')).events.length, 2));
check('prompt and tool text not retained', () => assert.ok(!JSON.stringify(parseSessionText(JSON.stringify({ type: 'response_item', payload: { text: 'PRIVATE_BODY_123' } }))).includes('PRIVATE_BODY_123')));
check('nested cache/reasoning fields', () => {
  const nested = { input_tokens: 30, input_tokens_details: { cached_tokens: 20 }, output_tokens: 10, output_tokens_details: { reasoning_tokens: 5 } };
  assert.deepEqual(aggregateSessions([parseSessionText(event(t1, nested))], 'all', 'UTC', now).details, { input: 30, cached: 20, output: 10, reasoning: 5, total: 40 });
});
check('historical total-only records are counted with partial detail notice', () => {
  const s = aggregateSessions([parseSessionText(event(t1, { total_tokens: 50 }))], 'all', 'UTC', now);
  assert.equal(s.total, 50); assert.equal(s.detailsIncomplete, true);
});
check('prefer grouped quotas without adding legacy duplicate', () => {
  const q = normalizeQuota({ rateLimits: { primary: { usedPercent: 90 } }, rateLimitsByLimitId: { codex: { primary: { usedPercent: 21, windowDurationMins: 300, resetsAt: 100 }, secondary: { usedPercent: 0, windowDurationMins: 10080, resetsAt: null } }, fast: { primary: { usedPercent: 150 } } } }, now);
  assert.deepEqual(q.windows.map(w => w.remainingPercent), [79, 100, 0]); assert.equal(q.windows[0].resetsAt, 100000); assert.equal(q.windows[1].resetsAt, null);
});
check('legacy quotas and missing windows', () => { assert.equal(normalizeQuota({ rateLimits: { primary: { usedPercent: 10 } } }).windows.length, 1); assert.equal(normalizeQuota({}).state, 'unavailable'); assert.equal(normalizeQuota({ rateLimits: { primary: { usedPercent: null } } }).windows.length, 0); });
const account = normalizeAccount({ summary: { lifetimeTokens: 1000, peakDailyTokens: 700 }, dailyUsageBuckets: [{ startDate: '2026-10-06', tokens: 300 }, { startDate: '2026-10-07', tokens: 700 }] }, now);
check('official lifetime is not added to daily tokens', () => assert.equal(accountStats(account, 'all', 'UTC', null).total, 1000));
check('official insufficient period returns null, not zero', () => assert.equal(accountStats(account, '30', 'UTC', null).total, null));
check('official null fields remain unavailable', () => assert.equal(accountStats(normalizeAccount({ summary: { lifetimeTokens: null }, dailyUsageBuckets: null }), 'all', 'UTC', null).total, null));
check('invalid daily bucket and duplicate rejected', () => { assert.throws(() => normalizeAccount({ summary: {}, dailyUsageBuckets: [{ startDate: 'bad', tokens: 5 }] })); assert.throws(() => normalizeAccount({ summary: {}, dailyUsageBuckets: [{ startDate: '2026-10-07', tokens: 5 }, { startDate: '2026-10-07', tokens: 5 }] })); });
check('DeepSeek amount and currency preserved', () => assert.deepEqual(deepseekBalance({ balance_infos: [{ currency: 'CNY', total_balance: '12.345', granted_balance: '2.345', topped_up_balance: '10.000' }] })[0], { currency: 'CNY', total: '12.345', granted: '2.345', toppedUp: '10.000' }));
check('invalid DeepSeek balance rejected', () => assert.throws(() => deepseekBalance({ balance_infos: [{ currency: 'CNY', total_balance: null }] })));
check('Alibaba cash balance preferred to available credit', () => { const a = parseConsoleBalance('账户可用额度（元） 500.00\n现金余额\n￥12.30', 'qwen')[0]; assert.equal(a.total, '12.30'); assert.equal(a.kind, 'balance'); });
check('Alibaba credit explicitly identified', () => assert.equal(parseConsoleBalance('账户可用额度（元）\n100.00', 'qwen')[0].kind, 'available_credit'));
check('Alibaba distinct cash accounts never guessed; unique available funds retains its label', () => { const result = parseConsoleBalance('现金余额 ￥2.00\n现金余额 ￥3.00\n账户可用额度 ￥5.00', 'qwen')[0]; assert.equal(result.total, '5.00'); assert.equal(result.kind, 'available_credit'); assert.throws(() => parseConsoleBalance('现金余额 ￥2.00\n现金余额 ￥3.00', 'qwen')); });
check('MiMo balance with currency', () => assert.equal(parseConsoleBalance('Account Balance\n$1,234.50', 'mimo')[0].currency, 'USD'));
check('MiMo current Chinese balance heading', () => assert.equal(parseConsoleBalance('账户余额\n余额\n78.25 元\n现金余额：60.00\n赠送余额：18.25\n信用余额 / 信用额度：0 / 0', 'mimo')[0].total, '78.25'));
check('MiMo current English balance heading', () => assert.equal(parseConsoleBalance('Account Balance\nBalance\n12.50\nUSD\nCash Balance: 10.00\nBonus Balance: 2.50', 'mimo')[0].currency, 'USD'));
check('MiMo sub-balances and credits never mistaken for total', () => { assert.throws(() => parseConsoleBalance('现金余额：60.00 元\n赠送余额：18.25 元\n信用余额 / 信用额度：1000 元', 'mimo')); assert.throws(() => parseConsoleBalance('Cash Balance: $60\nBonus Balance: $18.25\nCredit Balance / Credit Limit: $1000', 'mimo')); });
check('GLM balance reads actual zero', () => assert.equal(parseConsoleBalance('账户余额：0.00 元', 'glm')[0].total, '0.00'));
check('GLM financial overview current balance', () => assert.equal(parseConsoleBalance('费用中心\n当前余额\n33.37元\n去充值', 'glm')[0].total, '33.37'));
check('GLM report accepts actual zero and preserves decimal balance', () => { assert.equal(glmConsoleBalance({ data: { balance: 0 } })[0].total, '0'); assert.equal(glmConsoleBalance({ data: { balance: '4.238' } })[0].total, '4.238'); });
check('GLM unloaded report is not a zero balance', () => { assert.throws(() => glmConsoleBalance({ data: {} })); assert.throws(() => glmConsoleBalance({ data: { balance: null } })); });
check('no marketing price or token credits treated as cash', () => { assert.throws(() => parseConsoleBalance('Pro $44/mo\n充值余额\n1200积分', 'mimo')); assert.throws(() => parseConsoleBalance('账户余额 1000 credits', 'mimo')); });
check('ambiguous account values rejected', () => assert.throws(() => parseConsoleBalance('账户余额 ￥2.00\n账户余额 ￥3.00', 'glm')));

const root = path.resolve('.cache/usage-tests');
await mkdir(root, { recursive: true });
check('console navigation allows only official HTTPS domains', () => {
  assert.equal(allowedConsoleUrl('qwen', 'https://account.aliyun.com/login'), true);
  assert.equal(allowedConsoleUrl('glm', 'https://bigmodel.cn.attacker.example/login'), false);
  assert.equal(allowedConsoleUrl('mimo', 'http://platform.xiaomimimo.com/console/balance'), false);
});
let renderAttempts = 0;
assert.equal(await waitForBalance(async () => { if (++renderAttempts < 4) throw new Error('needs_login'); return 'ready'; }, async () => {}), 'ready');
checks++; console.log('PASS waits for asynchronous dashboard instead of treating loading as expired login');
await assert.rejects(() => waitForBalance(async () => { throw new Error('invalid_data'); }, async () => {}, 2), /invalid_data/);
checks++; console.log('PASS unreadable dashboard eventually fails without guessing');
const privateFile = path.join(root, 'session-state.dat');
const privateFixture = { cookies: [{ name: 'test', value: 'PRIVATE_SESSION_FIXTURE' }], origins: [] };
await savePrivateState(privateFile, privateFixture); assert.deepEqual(await loadPrivateState(privateFile), privateFixture);
if (process.platform === 'win32') assert.ok(!(await readFile(privateFile, 'utf8')).includes('PRIVATE_SESSION_FIXTURE'));
checks++; console.log('PASS private session survives restart and is encrypted for Windows user');
const polling = new BalanceService(path.join(root, 'polling'), () => {});
const fakePage = { goto: async () => { navigations++; }, waitForTimeout: async () => {} };
let launches = 0, navigations = 0, amountRead = 0, contextClosed = false;
const fakeContext = { pages: () => [fakePage], close: async () => { contextClosed = true; } };
(polling as any).contexts.set('mimo', fakeContext);
(polling as any).readPage = async () => [{ currency: 'CNY', total: String(++amountRead), granted: null, toppedUp: null }];
(polling as any).saveSession = async () => {};
(polling as any).launch = async () => { launches++; return fakeContext; };
await (polling as any).update('mimo'); await (polling as any).update('mimo');
assert.equal(launches, 0); assert.equal(navigations, 2); assert.equal(polling.snapshot().find(b => b.provider === 'mimo')!.amounts[0].total, '2'); assert.equal(contextClosed, false);
checks++; console.log('PASS reused background session reloads actual balance each time');
for (const provider of ['deepseek', 'qwen', 'mimo', 'glm']) (polling as any).values.get(provider).checkedAt = Date.now();
(polling as any).values.get('mimo').checkedAt = Date.now() - 61_000;
let dueReads = 0; (polling as any).update = async () => { dueReads++; };
await polling.refresh(); assert.equal(dueReads, 1);
checks++; console.log('PASS balances refresh after one minute rather than five');
await polling.close(); assert.equal(contextClosed, true); checks++; console.log('PASS background balance browser closes with application');
const glmLoading = new BalanceService(path.join(root, 'glm-loading'), () => {});
const loadingPage = { url: () => 'https://open.bigmodel.cn/finance-center/finance/overview', frames: () => [{ url: () => 'https://open.bigmodel.cn/finance-center/finance/overview', locator: () => ({ innerText: async () => '当前余额\n0 元' }) }] };
await assert.rejects(() => (glmLoading as any).readPage('glm', loadingPage), /invalid_data/);
(glmLoading as any).glmReports.set(loadingPage, Promise.resolve(glmConsoleBalance({ data: { balance: 8.25 } })));
assert.equal((await (glmLoading as any).readPage('glm', loadingPage))[0].total, '8.25');
checks++; console.log('PASS GLM trusts completed finance report rather than initial DOM zero');
const officialIframe = { url: () => 'https://usercenter2.aliyun.com/home', frames: () => [{ url: () => 'https://usercenter.aliyun.com/finance', locator: () => ({ innerText: async () => '账户可用额度（元）\n9.75' }) }, { url: () => 'https://untrusted.example/', locator: () => ({ innerText: async () => '账户可用额度（元）\n1000000' }) }, { url: () => 'https://free.aliyun.com/offer', locator: () => ({ innerText: async () => '账户可用额度（元）\n1000000' }) }] };
assert.equal((await (glmLoading as any).readPage('qwen', officialIframe))[0].total, '9.75');
checks++; console.log('PASS Alibaba official subdomain iframe is read without trusting foreign frames');
const fastGlm = new BalanceService(path.join(root, 'fast-glm'), () => {});
let reportCalls = 0, disposed = false;
(fastGlm as any).contexts.set('glm', { request: { get: async (_url: string, options: any) => { assert.equal(options.maxRedirects, 0); reportCalls++; return { ok: () => true, json: async () => ({ data: { balance: reportCalls } }), dispose: async () => { disposed = true; } }; } }, close: async () => {} });
(fastGlm as any).glmRequest = { url: 'https://open.bigmodel.cn/api/biz/account/query-customer-account-report', headers: { authorization: 'PRIVATE_FIXTURE' } };
await fastGlm.refresh(true, 'glm'); await fastGlm.refresh(true, 'glm');
assert.equal(reportCalls, 2); assert.equal(fastGlm.snapshot().find(b => b.provider === 'glm')!.amounts[0].total, '2'); assert.equal(disposed, true);
assert.ok(!JSON.stringify(fastGlm.snapshot()).includes('PRIVATE_FIXTURE'));
checks++; console.log('PASS GLM refresh reuses read-only report without navigating console or exposing credentials');
await fastGlm.close();
const home = path.join(root, 'codex'); await mkdir(path.join(home, 'sessions'), { recursive: true }); await mkdir(path.join(home, 'archived_sessions'), { recursive: true });
await writeFile(path.join(home, 'sessions', 'test.jsonl'), text); await writeFile(path.join(home, 'archived_sessions', 'same.jsonl'), text);
const scanner = new CodexScanner(home);
assert.equal((await scanner.read('all', 'UTC')).total, 250); checks++; console.log('PASS scanner reads current and archived without duplication');
assert.equal((await scanner.read('all', 'UTC')).total, 250); checks++; console.log('PASS repeated scan is idempotent');
const oldFetch = globalThis.fetch, oldKey = process.env.DEEPSEEK_API_KEY;
try {
  let calls = 0; process.env.DEEPSEEK_API_KEY = 'PRIVATE_TEST_KEY';
  globalThis.fetch = (async () => { calls++; return new Response(JSON.stringify({ balance_infos: [{ currency: 'CNY', total_balance: '4.20' }] }), { status: 200 }); }) as typeof fetch;
  const balances = new BalanceService(path.join(root, 'balances'), () => {});
  await Promise.all([balances.refresh(true), balances.refresh(true)]);
  assert.equal(calls, 1); checks++; console.log('PASS concurrent balance refresh coalesced');
  globalThis.fetch = (async () => { throw new Error('unavailable'); }) as typeof fetch;
  await balances.refresh(true); const b = balances.snapshot()[0]; assert.equal(b.state, 'stale'); assert.equal(b.amounts[0].total, '4.20'); checks++; console.log('PASS failed refresh retains actual prior balance');
  await balances.close();
} finally { globalThis.fetch = oldFetch; if (oldKey == null) delete process.env.DEEPSEEK_API_KEY; else process.env.DEEPSEEK_API_KEY = oldKey; }

const service = new UsageService(path.join(root, 'service'), home);
await (service as any).initialized;
let rpcCalls = 0;
(service as any).client = { read: async () => { rpcCalls++; return { quota: { status: 'fulfilled', value: { rateLimits: { primary: { usedPercent: 20 } } } }, account: { status: 'fulfilled', value: { summary: { lifetimeTokens: 999 }, dailyUsageBuckets: null } } }; }, close: async () => {} };
(service as any).balances = { refresh: async () => {}, snapshot: () => [], close: async () => {}, connect: async () => {} };
await Promise.all([service.overview('all', 'account', 'UTC', true), service.overview('all', 'local', 'UTC', true)]);
assert.equal(rpcCalls, 1); checks++; console.log('PASS concurrent Codex reads coalesced');
assert.equal((await service.overview('all', 'account', 'UTC')).stats.total, 999); assert.equal((await service.overview('all', 'local', 'UTC')).stats.total, 250); checks++; console.log('PASS account and local totals stay separate');
const app = express(); app.use(express.json()); app.use('/api/usage', createUsageRouter(service));
let releaseBalance!: () => void;
const slowBalance = new Promise<void>(resolve => { releaseBalance = resolve; });
(service as any).balances = { refresh: async () => { await slowBalance; }, snapshot: () => [{ ...emptyBalance('mimo'), refreshing: true }], close: async () => {} };
const quickView = await service.overview('all', 'account', 'UTC', false, true);
assert.equal(quickView.refreshing, true); assert.equal(quickView.stats.total, 999);
checks++; console.log('PASS slow provider does not delay cached overview or other account results');
releaseBalance();
(service as any).balances = { refresh: async () => { throw new Error('poll must not refresh'); }, snapshot: () => [], close: async () => {} };
assert.equal((await service.overview('all', 'account', 'UTC', false, true, true)).refreshing, false);
checks++; console.log('PASS progress polling does not restart provider requests');
(service as any).balances = { refresh: async () => {}, snapshot: () => [], close: async () => {}, connect: async () => {} };
const server = app.listen(0, '127.0.0.1'); await new Promise<void>(resolve => server.once('listening', resolve));
const address = server.address() as { port: number }; const base = `http://127.0.0.1:${address.port}/api/usage`;
try {
  assert.equal((await fetch(`${base}/refresh`, { method: 'POST', headers: { Origin: 'https://untrusted.example', 'Content-Type': 'application/json' }, body: '{}' })).status, 403); checks++; console.log('PASS cross-origin refresh refused');
  assert.equal((await fetch(`${base}/accounts/arbitrary/connect`, { method: 'POST' })).status, 400); checks++; console.log('PASS arbitrary provider refused');
  assert.equal((await fetch(`${base}/overview?range=bad`)).status, 400); assert.equal((await fetch(`${base}/overview?timezone=bad`)).status, 400); checks++; console.log('PASS invalid range/timezone refused');
  const response = await fetch(`${base}/overview?scope=local`); assert.equal(response.status, 200); const json = await response.text(); assert.ok(!json.includes('PRIVATE_TEST_KEY')); assert.ok(!json.includes('PRIVATE_BODY_123')); checks++; console.log('PASS API only returns usage metadata');
} finally { await new Promise<void>(resolve => server.close(() => resolve())); await service.close(); }
const restored = new UsageService(path.join(root, 'service'), home); await (restored as any).initialized;
assert.equal((restored as any).account.lifetimeTokens, 999); assert.equal((restored as any).quota.state, 'stale'); checks++; console.log('PASS restart restores cache as stale until refreshed');
await restored.close();
// Delete only this test-owned directory within the workspace cache.
assert.ok(root.startsWith(path.resolve('.cache') + path.sep)); await rm(root, { recursive: true, force: true });
console.log(`${checks} usage checks passed`);
